/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

description = "Using OpenTelemetry via the Agent"
val moduleName by extra { "net.scaffidi.otel.agentexample" }

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "net.scaffidi.otel.agentexample.Main"
}

val agent = configurations.create("agent")

dependencies {
    implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.13.1")
    agent("io.opentelemetry.javaagent:opentelemetry-javaagent:2.13.1")
}

val copyAgent = tasks.register<Copy>("copyAgent") {
    from(agent.singleFile)
    into(layout.buildDirectory.dir("agent"))
    rename("opentelemetry-javaagent-.*\\.jar", "opentelemetry-javaagent.jar")
}

tasks.named<JavaExec>("run") {
    dependsOn(copyAgent)
    environment("JAVA_TOOL_OPTIONS", "-javaagent:" + "build/agent/opentelemetry-javaagent.jar")
}
