---
name: Update Version
on:
  push:
    branches:
    - main
env:
  CURRENT_VERSION_TOP_LEVEL: 'foo/bar/v2.11.7'

jobs:
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
  get_new_version:
    runs-on: ubuntu-latest
    steps:
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.2.3
      with:
        current-version: ${{ env.CURRENT_VERSION_TOP_LEVEL }} # also accepted: 'v2.11.7-alpha.3' | '2.11.7-alpha3'
        version-fragment: 'patch'
    - name: Do something with your bumped release version
      run: echo ${{ steps.bump_version.outputs.next-version }} # will print 2.12.0
