---
name: Update Version
on:
  push:
    branches:
    - main
env:
  CURRENT_VERSION_TOP_LEVEL: 'v2.11.7'

jobs:
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    outputs:
      tags: ${{ steps.get_tags.outputs.tags }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          fetch-tags: true  # to ensure we get tags
      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files_from_source_file: 'auto-tag-dirs.txt'
      - name: list all changed files
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "### TAGS"
          git tag --list > tags.txt
          cat tags.txt

          echo "### TAG PREFIXES"
          git tag --list | sed 's|/[^/]*$||' > tag-prefixes.txt
          cat tag-prefixes.txt

          echo "### CHANGED FILES"
          echo "${CHANGED_FILES}" > changed-files.txt
          cat changed-files.txt

          echo "### PREFIXES MATCHING CHANGED FILES"
          grep -o -f tag-prefixes.txt changed-files.txt > matching-prefixes.txt
          cat matching-prefixes.txt

          echo "### TAGS TO UPDATE"
          grep -f matching-prefixes.txt tags.txt > tags-to-update.txt
          cat tags-to-update.txt

      - name: get tags to update
        id: get_tags
        run: |
          echo "### TAGS TO UPDATE"
          echo "tags=[$(sed 's/\(.*\)/\"\1\"/;s/\n$//;2,$s/^/,/' tags-to-update.txt)]"
          echo "tags=[$(sed 's/\(.*\)/\"\1\"/;s/\n$//;2,$s/^/,/' tags-to-update.txt)]" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: changed_files
    steps:
      - env:
          OUTPUT1: ${{needs.changed_files.outputs.tags}}
        run: echo "$OUTPUT1"

  get_new_version:
    runs-on: ubuntu-latest
    steps:
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.2.3
      with:
        current-version: ${{ env.CURRENT_VERSION_TOP_LEVEL }}
        version-fragment: 'patch'
    - name: Do something with your bumped release version
      run: echo ${{ steps.bump_version.outputs.next-version }}
